### ISSUE TITLE
PLugin lädt nicht

### ISSUE THREAD

**Issue by Bruhh1234** [MonoAdrian23/TimeFly#1]
war mein fehler, Könntest du die option hinufügen die abklingzeit zu deaktivieren ?

LG

**Comment by MonoAdrian23** [comment]
Oh vielen Dank, habe ich gerade gesehen. Ich behebe es sofort.
Mit freundlichen Grüßen

Bruhh1234 <notifications@github.com> schrieb am Mi., 9. Sept. 2020, 12:17:

**Comment by Bruhh1234** [comment]
ja wenn man die Phar nimmt und die Config in PL Data koopiert geht es.

wie ist es mit der Abklingzeit (jetzt durfen alle 1x pro tag ?) würde das gerne configurierbar haben :)

danke für die schnelle Antwort :)

**Comment by MonoAdrian23** [comment]
Wenn ein Spieler /fboost verwendet, darf er aller 24 Stunden für exakt 20 Minuten den Boost aktivieren.
Ich werde aber noch eine Bypass Permission hinzufügen.

**Comment by Bruhh1234** [comment]
was muss ich machen dammit der boost nur dem spieler der ihn aktiviert Fly verpasst ?.

LG

**Comment by MonoAdrian23** [comment]
Der Flybooster ist für alle da, es ist nicht gedacht gewesen diesen für einzelne Spieler zu programmieren. 
Mit der Permission fboost.cmd kannst du Rängen deiner Wahl eine Berechtigung geben wer den Booster aktivieren darf.

**Comment by Bruhh1234** [comment]
Ja das sah ich bereits xD,

frage mich wie es ausehen müsste 
getOnlinePlayers() as $player){

also was genau ich ändern müsste um diesen booster nur für mich zu aktivieren xD
das mit der Permission ist schon gut so 👍

**Comment by Bruhh1234** [comment]
Wäre nice wenn du mir da Weiterhelfen kannst :)

**Comment by MonoAdrian23** [comment]
Wie gesagt, der Booster ist nur dafür gedacht allen Fly zu geben.
Du kannst natürlich den Booster auf deine Wünsche so Coden wie du es magst.
Spricht nix dagegen
